# Generated by Django 4.0.4 on 2022-07-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('link', models.URLField(blank=True, max_length=100)),
                ('add1', models.CharField(blank=True, max_length=50)),
                ('add2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('hobby1', models.BooleanField(default=False, verbose_name='reading_books')),
                ('hobby2', models.BooleanField(default=False, verbose_name='travelling')),
                ('hobby3', models.BooleanField(default=False, verbose_name='listening_music')),
            ],
        ),
    ]
