# Generated by Django 4.0.4 on 2022-07-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_api', '0002_remove_student_data_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data',
            name='link',
        ),
    ]
