# Generated by Django 4.1.5 on 2023-06-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='class_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=25)),
                ('class_room', models.IntegerField()),
                ('std_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_detail', to='app7_api.student_detail')),
            ],
        ),
    ]
